"""Add User model

Revision ID: 121cbd351fad
Revises: a28af33e6866
Create Date: 2023-09-04 10:48:20.326681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121cbd351fad'
down_revision = 'a28af33e6866'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reviews_game_id_games', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_game_id_games', 'games', ['game_id'], ['id'])
        batch_op.drop_column('user_id')

    op.drop_table('users')
    # ### end Alembic commands ###
